name: Testing
on:
  - push


jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: action_time
        with:
          format: YYYY-MM-DD HH:MM:SS Z
          utcOffset: "-08:00"
      - name: make own time
        id: bash_time
        run: |
          echo "::set-output formattedTime=$(TZ=UTC+8 date +%Y-%m-%d %H:%M:%S %z)"
      - name: echo action time
        run: |
          echo "ACTION TIME: ${{ steps.action_time.outputs.formattedTime }}"
          echo "  BASH TIME: ${{ steps.bash_time.outputs.formattedTime }}"
